version: '2'

services:
  cassandra:
    image: cassandra:3.11.1
    env_file:
      - env/cassandra.env
    # uncomment this line if you're using OSX
    # Linux environments require extra logic to explictly set the correct permissions
    # volumes:
    #   - ./cassandra/data:/var/lib/cassandra

  cqlsh:
    image: cassandra:3.11.1
    command: cqlsh cassandra

  load-schema:
    image: cassandra:3.11.1
    command: cqlsh cassandra -f /schema.cql
    volumes:
      - ./cassandra/schema.cql:/schema.cql

  load-data:
    build: .
    command: ./bin/01.load.py
    env_file:
      - env/cassandra.env
    volumes:
      - .:/opt

  analyze:
    build: .
    command: ./bin/02.analyze.py
    env_file:
      - env/cassandra.env
    volumes:
      - .:/opt
